server:
  port: 8080

spring:
  application:
    name: surgeops-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# CORS configuration.  Origins are supplied via environment variables.
cors:
  allowed-origins: ${ALLOWED_ORIGINS}

# Custom application properties
app:
  chat:
    mode: ${APP_CHAT_MODE:db-hybrid}
  kafka:
    enabled: ${APP_KAFKA_ENABLED:false}

weather:
  provider: ${WEATHER_PROVIDER:open-meteo}
  recencyMinutes: ${WEATHER_RECENCY_MINUTES:30}

azure:
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT:}
    api-key: ${AZURE_OPENAI_API_KEY:}
    api-version: ${AZURE_OPENAI_API_VERSION:2024-06-01}
    chat-deployment: ${AZURE_OPENAI_CHAT_DEPLOYMENT:gpt-4o-mini}
    embeddings-deployment: ${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT:text-embedding-3-large}
    embedding-dim: ${EMBEDDING_DIM:1536}