package com.surgeops.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.GenericGenerator;

import java.time.Instant;
import java.util.UUID;

/**
 * Entity representing an alert generated by the surge detection system or other processes.
 */
@Entity
@Table(name = "alerts")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Alert {

    @Id
    @Column(name = "alert_id", nullable = false, updatable = false)
    private UUID alertId;

    @Column(name = "surge_id")
    private UUID surgeId;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    @Enumerated(EnumType.STRING)
    @Column(name = "severity")
    private AlertSeverity severity;

    @Column(name = "message", nullable = false)
    private String message;

    @Column(name = "acknowledged", nullable = false)
    private Boolean acknowledged = false;

    @Column(name = "suggestion_action")
    private String suggestionAction;

    @Column(name = "suggestion_from_block")
    private String suggestionFromBlock;

    @Column(name = "suggestion_to_block")
    private String suggestionToBlock;

    @Column(name = "suggestion_teu")
    private Integer suggestionTeu;
}